return PlaceObj('ModDef', {
	'title', "Recoloured Dome Bonus Icons",
	'description', "This mod changes the colours of the Vista and Research dome bonus map icons to more distinctive colours. I've often found that the Vista and Research Icons were too similar to the Rare Metals and Water Icons respectively at a quick glance. This mode aims to alter that quick glance perception.\n\nSpecial Thanks to:\nChoGGi for creating the base mod; \nhttps://steamcommunity.com/sharedfiles/filedetails/?id=1581373413\nLukeH for fixing texture issues on fallback\nDawnMist for catching a LogError\nEaglescout93 for Modding Support",
	'image', "Preview.PNG",
	'last_changes', "Fixed;\nReduced filesize of fallback textures",
	'id', "fLSOMe5",
	'steam_id', "1582890631",
	'pops_desktop_uuid', "d1c97e77-716f-4964-b345-3d7f958ae2f0",
	'pops_any_uuid', "9979895c-fd08-4bed-99da-b407e90a0f98",
	'author', "RustyDios",
	'version', 22,
	'lua_revision', 233360,
	'saved_with_revision', 244677,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1559009533,
	'screenshot1', "Preview.PNG",
	'screenshot2', "ResearchIconPreveiw.PNG",
	'screenshot3', "VistaIconPreview.PNG",
	'screenshot4', "Preview2.PNG",
	'TagCosmetics', true,
	'TagInterface', true,
	'TagOther', true,
})